<!-- This is a template for a standard article
- Do not edit this file, it is a template for other articles
-->

<!-- Start of the template -->

!!! note "Note Title"

    Note Body. Add your content here.

<div style="height: 20px;"></div>

## Header 1

This is a paragraph. Paragraphs are separated by a blank line. Add your content here. You can use **bold** and _italic_ text.

You can use links like this: [Link Text](URL){:target="\_blank"}

You can use images like this: ![Image Description](image.png)

### Header 2

This is a unordered list.

- Item 1
- Item 2
- Item 3

#### Header 3

This is an ordered list.

1. Item 1
2. Item 2
3. Item 3

##### Header 4

This is a table.

| Header 1 | Header 2 | Header 3 |
| -------- | -------- | -------- |
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |
| Cell 7   | Cell 8   | Cell 9   |

###### Header 5

This is a blockquote.

> Blockquote content. Add your content here.

This is a note.

## References

References are footnotes that are added at the end of the article.
Use this format:

[^1]: [Reference Text](www.byui.edu/example){:target="\_blank"}

<!-- End of the template -->
